export const defaultImports = {
  vue: 'https://play.vuejs.org/vue.runtime.esm-browser.js',
  debounce: 'https://cdn.jsdelivr.net/npm/debounce/+esm',
  '@vueuse/core': 'https://unpkg.com/@vueuse/core@10.1.0/index.mjs',
  '@vueuse/shared': 'https://unpkg.com/@vueuse/shared@10.1.0/index.mjs',
  'vue/server-renderer': 'https://play.vuejs.org/server-renderer.esm-browser.js',
  quasar: 'https://cdn.jsdelivr.net/npm/quasar@2.13.0/dist/quasar.esm.prod.js',
  '@vuemodel/core': 'https://cdn.jsdelivr.net/npm/@vuemodel/core/dist/index.mjs',
  '@vuemodel/indexeddb': 'https://cdn.jsdelivr.net/npm/@vuemodel/indexeddb/dist/index.mjs',
  '@vuemodel/sample-data': 'https://cdn.jsdelivr.net/npm/@vuemodel/sample-data/dist/index.js',
  pinia: 'https://cdn.jsdelivr.net/npm/pinia@2.1.7/dist/pinia.esm-browser.js',
  'pinia-orm': 'https://cdn.jsdelivr.net/npm/pinia-orm@1.7.2/dist/index.mjs',
  'pinia-orm/dist/decorators': 'https://cdn.jsdelivr.net/npm/pinia-orm@1.7.2/dist/decorators.mjs',
  'deepmerge-ts': 'https://cdn.jsdelivr.net/npm/deepmerge-ts@5.1.0/dist/node/index.mjs',
  uuid: 'https://jspm.dev/uuid',
  '@pinia-orm/normalizr': 'https://cdn.jsdelivr.net/npm/@pinia-orm/normalizr@1.7.0/dist/index.mjs',
  'vue-demi': 'https://cdn.jsdelivr.net/npm/vue-demi@0.14.6/lib/index.mjs',
  '@vue/devtools-api': 'https://cdn.jsdelivr.net/npm/@vue/devtools-api@6.5.1/lib/esm/index.js',
  'just-clone': 'https://cdn.jsdelivr.net/npm/just-clone/+esm',
  'deep-equal': 'https://cdn.jsdelivr.net/npm/deep-equal/+esm',
  'just-index': 'https://cdn.jsdelivr.net/npm/just-index/+esm',
  'just-remove': 'https://cdn.jsdelivr.net/npm/just-remove/+esm',
  'just-omit': 'https://cdn.jsdelivr.net/npm/just-omit/+esm',
}
